<?php

namespace App\Http\Controllers\Admin;

use Shibby\Loilerplate\Controller\BaseController;
use Carbon\Carbon;

class AdminController extends BaseController
{
    protected $parameters = [
        'siteTitle' => 'haritasi.biz',
        'siteDescription' => 'haritasi.biz',
        'pageTitle' => '',
    ];

    protected $og = [
        'type' => '',
        'title' => '',
        'image' => '',
        'url' => '',
        'video' => '',
    ];
    //use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    protected function setSiteTitle($title)
    {
        $this->setOg('title', $title);
        parent::setSiteTitle($title);
    }

    public function renderView($view, $params = [])
    {
        if(empty($this->og['url'])){
            $this->og['url'] = \Request::getUri();
        }
        $params['og'] = $this->og;
        $params['current_url'] = url()->current();
        $params['dateToday'] = Carbon::today()->formatLocalized('%d %B %Y');

        return parent::renderView($view, $params); // TODO: Change the autogenerated stub
    }
}
